name: 파일처리 과제 3 CI 테스트 스크립트

on:
  push:
    paths:
      - '**.c'
      - '**.h'
      - '.github/workflows/test.yml'
  pull_request:

jobs:
  test-ftl_open:
    name: ftl_open() test
    runs-on: ubuntu-22.04
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: TEST_FTL_OPEN 플래그로 컴파일
        run: gcc main.c ftlmgr.c fdevicedriver.c -o a.out

      - name: ftl_open 테스트 실행
        run: ./a.out

  test-ftl_write:
    name: ftl_write() test
    runs-on: ubuntu-22.04
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: TEST_FTL_WRITE 플래그로 컴파일
        run: gcc main.c ftlmgr.c fdevicedriver.c -o a.out

      - name: ftl_write 테스트 실행
        run: ./a.out

  test-ftl_read:
    name: ftl_read() test
    runs-on: ubuntu-22.04
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: TEST_FTL_READ 플래그로 컴파일
        run: gcc main.c ftlmgr.c fdevicedriver.c -o a.out

      - name: ftl_read 테스트 실행
        run: ./a.out

  test-ftl_print:
    name: ftl_print() test
    runs-on: ubuntu-22.04
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: TEST_FTL_PRINT 플래그로 컴파일
        run: gcc main.c ftlmgr.c fdevicedriver.c -o a.out

      - name: ftl_print 테스트 실행
        run: ./a.out